### ISSUE TITLE
Stop creating empty repositories

### ISSUE THREAD

**Issue by fwhcat** [unlimitedsoftwareworks/ryu#1]
lel

**Comment by younishd** [comment]
![](http://i.memeful.com/media/post/1RXGGDM_700wa_0.gif)

**Comment by praisethemoon** [comment]
![japan-riding-dirty](https://cloud.githubusercontent.com/assets/22145460/24514992/6ec106c8-1576-11e7-841e-65403a6a364d.jpg)
